In [18]:
import numpy as np
from scipy.sparse.linalg import eigsh
import scipy.sparse as sparse
from scipy.linalg import eigh
import scipy.linalg
import matplotlib.pyplot as plt
from qutip import *
import math

In [19]:
#plt.rcParams['figure.figsize']=8.5,5.1
plt.rcParams['font.size']=20
plt.rcParams['lines.linewidth']=1.5
plt.rcParams['text.usetex']=True

In [20]:
#Construction of necessary elements of theta and phi Hilbert spaces

# For phi

N=50
a_phi=np.diag(np.sqrt(np.arange(1, N+1)), 1)
ad_phi=np.diag(np.sqrt(np.arange(1, N+1)), -1)
N_phi=ad_phi@a_phi
Id_N=np.eye(N+1)

# For theta

M=20
Id_M=np.eye(2*M+1)
n_theta=np.flipud(np.fliplr(np.diag(np.arange(-M,M+1), 0)))

#Values of equilibrium

phi_ext_val=np.pi
ng_val=0.5

#Qubit parameters 1 

E_Cs=1.0
E_Cj=1.0
E_L=1.0
E_J=1.0
alpha=(1j*(E_Cj/E_L)**(1.0/4.0))

# Qubit parameters 2

E_Cs_2=(1.0/20)
E_Cj_2=1.0
E_L_2=(1.0/16)
E_J_2=(1.0/5.0)
alpha2=(1j*(E_Cj_2/E_L_2)**(1.0/4.0))

#FOR EXPECTATION VALUES

#PHI
print("PHI")
print((E_Cj/E_L)**(1.0/4.0)*(a_phi+ad_phi))
phi=np.kron(Id_M,((E_Cj/E_L)**(1.0/4.0))*(a_phi+ad_phi))
print("kron PHI")
print(phi)
phi2=np.kron(Id_M,((E_Cj_2/E_L_2)**(1.0/4.0))*(a_phi+ad_phi))

#COS_THETA
costheta=np.diag(np.ones(2*M),1)+np.diag(np.ones(2*M),-1) 
costheta[0][2*M]+=1
costheta[2*M][0]+=1
print(costheta)
print("COS")
cos_theta=np.kron(costheta,Id_N)
print("kron COS")
print(cos_theta)

#N_PHI
N_phi_extended=np.kron(Id_M,N_phi)

#N_theta
n_theta_extended=np.kron(n_theta,Id_N)


#FOR SAVING VALUES OF CALCULATIONS

#NG

#1

#ng1=np.arange(0.5-0.01*0.5 , 0.5+0.01*0.5 + 0.001 , 0.01*0.5*2)
#ng2=np.arange(0.5-0.01*0.5 , 0.5+0.01*0.5 + 0.001 , 0.01*0.5*2)
#print(r"(1%) \epsilon_n = ",0.01*0.5)
#epsilon_n=0.01*0.5
#print(ng1)

#2

#ng1=np.arange(0.5-0.015*0.5 , 0.5+0.015*0.5 + 0.001 , 0.015*0.5*2)
#ng2=np.arange(0.5-0.015*0.5 , 0.5+0.015*0.5 + 0.001 , 0.015*0.5*2)
#print(r"(1.5%) \epsilon_n = ",0.015*0.5)
#epsilon_n=0.015*0.5
#print(ng1)

#3

#ng1=np.arange(0.5-0.005*0.5 , 0.5+0.005*0.5 + 0.001 , 0.005*0.5*2)
#ng2=np.arange(0.5-0.005*0.5 , 0.5+0.005*0.5 + 0.001 , 0.005*0.5*2)
#print(r"(0.5%) \epsilon_n = ",0.005*0.5)
#epsilon_n=0.005*0.5
#print(ng1)

#4

ng1=np.arange(0.5-0.0075*0.5 , 0.5+0.0075*0.5 + 0.001 , 0.0075*0.5*2)
ng2=np.arange(0.5-0.0075*0.5 , 0.5+0.0075*0.5 + 0.001 , 0.0075*0.5*2)
print(r"(0.75%) \epsilon_n = ",0.0075*0.5)
epsilon_n=0.0075*0.5
print(ng1)

#PHIEXT

#1

#a=np.pi-(np.pi*0.022776)
#b=np.pi+(np.pi*0.022776 + 0.001)
#phi_ext1=np.arange(a,b,(0.022776*np.pi)*2)
#phi_ext2=np.arange(a,b,(0.022776*np.pi)*2)
#print(r"(2.2776%) \epsilon_{\varphi} = ",(0.022776*np.pi))
#epsilon_phi=(0.022776*np.pi)
#print(phi_ext1)

#2

#a=np.pi-(np.pi*0.034172)
#b=np.pi+(np.pi*0.034172 + 0.001)
#phi_ext1=np.arange(a,b,(0.034172*np.pi)*2)
#phi_ext2=np.arange(a,b,(0.034172*np.pi)*2)
#print(r"(3.4172%) \epsilon_{\varphi} = ",(0.034172*np.pi))
#epsilon_phi=(0.034172*np.pi)
#print(phi_ext1)

#3

#a=np.pi-(np.pi*0.0113864)
#b=np.pi+(np.pi*0.0113864 + 0.001)
#phi_ext1=np.arange(a,b,(0.0113864*np.pi)*2)
#phi_ext2=np.arange(a,b,(0.0113864*np.pi)*2)
#print(r"(1.13864%) \epsilon_{\varphi} = ",(0.0113864*np.pi))
#epsilon_phi=(0.0113864*np.pi)
#print(phi_ext1)

#4

a=np.pi-(np.pi*0.0170807)
b=np.pi+(np.pi*0.0170807 + 0.001)
phi_ext1=np.arange(a,b,(0.0170807*np.pi)*2)
phi_ext2=np.arange(a,b,(0.0170807*np.pi)*2)
print(r"(1.70807%) \epsilon_{\varphi} = ",(0.0170807*np.pi))
epsilon_phi=(0.0170807*np.pi)
print(phi_ext1)

#1ST VALUES

Energies=[]
Eigenvectors=[]

Expvals_costheta_NG=[]
Expvals_phi_NG=[]
Expvals_N_phi_NG=[]
Expvals_n_theta_NG=[]

Expvals_costheta_PHIEXT=[]
Expvals_phi_PHIEXT=[]
Expvals_N_phi_PHIEXT=[]
Expvals_n_theta_PHIEXT=[]

Overlaps_NG=[]
Overlaps_PHIEXT=[]

EIGENVECTS_NG=[]
EIGENVECTS_PHIEXT=[]

Overlaps_UP_NG=[]
Overlaps_UP_PHIEXT=[]
Overlaps_SIDE_NG=[]
Overlaps_SIDE_PHIEXT=[]
Overlaps_CROSSED_NG=[]
Overlaps_CROSSED_PHIEXT=[]

#2ND VALUES

Energies2=[]
Eigenvectors2=[]

Expvals2_costheta_NG=[]
Expvals2_phi_NG=[]
Expvals2_N_phi_NG=[]
Expvals2_n_theta_NG=[]

Expvals2_costheta_PHIEXT=[]
Expvals2_phi_PHIEXT=[]
Expvals2_N_phi_PHIEXT=[]
Expvals2_n_theta_PHIEXT=[]

Overlaps2_NG=[]
Overlaps2_PHIEXT=[]

EIGENVECTS2_NG=[]
EIGENVECTS2_PHIEXT=[]

Overlaps2_UP_NG=[]
Overlaps2_UP_PHIEXT=[]
Overlaps2_SIDE_NG=[]
Overlaps2_SIDE_PHIEXT=[]
Overlaps2_CROSSED_NG=[]
Overlaps2_CROSSED_PHIEXT=[]


PHI
[[0.         1.         0.         ... 0.         0.         0.        ]
 [1.         0.         1.41421356 ... 0.         0.         0.        ]
 [0.         1.41421356 0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         7.         0.        ]
 [0.         0.         0.         ... 7.         0.         7.07106781]
 [0.         0.         0.         ... 0.         7.07106781 0.        ]]
kron PHI
[[0.         1.         0.         ... 0.         0.         0.        ]
 [1.         0.         1.41421356 ... 0.         0.         0.        ]
 [0.         1.41421356 0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         7.         0.        ]
 [0.         0.         0.         ... 7.         0.         7.07106781]
 [0.         0.         0.         ... 0.         7.07106781 0.        ]]
[[0. 1. 0. ... 0. 0. 1.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1

In [21]:
# Construction of the 0-pi Hamiltonian

def Hamiltonian_0pi(EJ,ECS,ECJ,EL,n,phi,alph):
    #Initial
    H=np.zeros(((2*M+1)*(N+1),(2*M+1)*(N+1)))
    #Free Hamiltonian construction
    H1=4*ECS*((n_theta-n*Id_M)@(n_theta-n*Id_M))
    H_theta=np.kron(H1,Id_N)
    H2=2*np.sqrt(ECJ*EL)*(N_phi+0.5*Id_N)
    H_phi=np.kron(Id_M,H2)
    H_0=H_theta+H_phi
    #H_0=np.zeros(((2*M+1)*(N+1),(2*M+1)*(N+1)))
    #Interaction Hamiltonian construction
    cos_theta_ext=np.diag(np.ones(2*M),1)+np.diag(np.ones(2*M),-1) 
    #cos_theta=np.diag(np.ones(2*M-1),2)+np.diag(np.ones(2*M-1),-2)
    cos_theta_ext[0][2*M]+=1
    cos_theta_ext[2*M][0]+=1
    #cos_phi=(0.5*((displace(N+1,alph)*(math.e**(-1j*phi/2)))+(displace(N+1,-alph)*(math.e**(1j*phi/2)))))*np.diag(np.ones(N+1),0)
    cos_phi=0.5*(scipy.linalg.expm(alph*(a_phi+ad_phi)-(Id_N*1j*phi/2))+scipy.linalg.expm(-alph*(a_phi+ad_phi)+(Id_N*1j*phi/2)))
    H_I=EJ*np.kron(cos_theta_ext,cos_phi.real)#SIN EL2 
    #H_I=np.zeros(((2*M+1)*(N+1),(2*M+1)*(N+1)))
    #Total Hamiltonian
    H+=H_0-H_I
    return H

In [22]:
def calculate_expval(vect,operator):
    return np.conj(vect)@operator@vect

In [23]:
def calculate_overlap(vect1,vect2):
    return np.abs(np.conj(vect1)@vect2)**2

In [24]:
Vprueba=[1,1,0]
Vprueba2=[0,2,0]
print(Vprueba)
O=calculate_overlap(Vprueba,Vprueba2)
print("O=",O)
matrix=[[0,1,0],[1,0,1],[0,1,0]]
print(matrix)
a=calculate_expval(Vprueba,matrix)
print(a)


[1, 1, 0]
O= 4
[[0, 1, 0], [1, 0, 1], [0, 1, 0]]
2


In [25]:
Vs=[]
V1=np.array([1,1,0])
V2=np.array([0,2,0])
V3=np.array([1,1,1])
Vs.extend([V1,V2,V3])
print(Vs)
print(Vs[0])
print(calculate_overlap(Vs[0],Vs[1]))


[array([1, 1, 0]), array([0, 2, 0]), array([1, 1, 1])]
[1 1 0]
4


## $\text{1. Plot for } E_{Cs} = E_{Cj} = E_L = 1$, $\varphi_{ext}= \pi$, $\alpha = i \left(\frac{E_{CJ}}{E_L}\right)^{1/4} = i$.

In [26]:
# Calculations 1

for n1 in ng1:
    print("Step for ng = ",n1)
    H1=Hamiltonian_0pi(E_J,E_Cs,E_Cj,E_L,n1,phi_ext_val,alpha)
    print("Hamiltonian built, len(H)=",len(H1)**2)
    #vals,vects=np.linalg.eigh(H)
    valsNG, vectsNG = eigsh(H1, k=2, which='SA')
    #vals,_=np.linalg.eigh(H)
    print("The eigenvalues of the GS and the 1st excited state are ",valsNG[0]," and ",valsNG[1])
    print("The eigenvectors of the GS and the 1st excited state are ",vectsNG[:,0]," and ",vectsNG[:,1])
    EIGENVECTS_NG.extend([vectsNG[:,0],vectsNG[:,1]])
    print(EIGENVECTS_NG)
    print("Eigenvalues and eigenvectors calculated")
    #Cos_theta
    Expval_costheta_0=calculate_expval(vectsNG[:,0],cos_theta)
    Expval_costheta_1=calculate_expval(vectsNG[:,1],cos_theta)
    #Phi
    Expval_phi_0=calculate_expval(vectsNG[:,0],phi)
    Expval_phi_1=calculate_expval(vectsNG[:,1],phi)
    #N_phi
    Expval_N_phi_0=calculate_expval(vectsNG[:,0],N_phi_extended)
    Expval_N_phi_1=calculate_expval(vectsNG[:,1],N_phi_extended)
    #n_theta
    Expval_n_theta_0=calculate_expval(vectsNG[:,0],n_theta_extended)
    Expval_n_theta_1=calculate_expval(vectsNG[:,1],n_theta_extended)
    #Overlap between the states of the same value of ng
    Overlap=calculate_overlap(vectsNG[:,0],vectsNG[:,1])
    print("Overlap = ",Overlap)
    #TOTALS
    Overlaps_NG.append(Overlap)
    Expvals_costheta_NG.extend([Expval_costheta_0,Expval_costheta_1])
    Expvals_phi_NG.extend([Expval_phi_0,Expval_phi_1])
    Expvals_N_phi_NG.extend([Expval_N_phi_0,Expval_N_phi_1])
    Expvals_n_theta_NG.extend([Expval_n_theta_0,Expval_n_theta_1])

Step for ng =  0.49625
Hamiltonian built, len(H)= 4372281
The eigenvalues of the GS and the 1st excited state are  1.7592472093895737  and  1.7846688185536905
The eigenvectors of the GS and the 1st excited state are  [ 2.35059901e-18 -2.04773366e-18 -1.74902001e-20 ...  9.11372007e-18
  2.74424810e-18 -7.42506227e-17]  and  [-9.76166717e-20 -2.95925664e-18  7.87527561e-19 ... -1.29280910e-19
 -4.38227876e-18 -7.15299682e-17]
[array([ 2.35059901e-18, -2.04773366e-18, -1.74902001e-20, ...,
        9.11372007e-18,  2.74424810e-18, -7.42506227e-17]), array([-9.76166717e-20, -2.95925664e-18,  7.87527561e-19, ...,
       -1.29280910e-19, -4.38227876e-18, -7.15299682e-17])]
Eigenvalues and eigenvectors calculated
Overlap =  2.728145353527852e-30
Step for ng =  0.50375
Hamiltonian built, len(H)= 4372281
The eigenvalues of the GS and the 1st excited state are  1.7592472093898057  and  1.7846688185536193
The eigenvectors of the GS and the 1st excited state are  [ 4.36244619e-18  1.59047503e-17 -

In [27]:
# Calculations 1

for phi1 in phi_ext1:
    print("Step for phi_ext = ",phi1)
    H2=Hamiltonian_0pi(E_J,E_Cs,E_Cj,E_L,ng_val,phi1,alpha)
    print("Hamiltonian built, len(H)=",len(H2)**2)
    #vals,vects=np.linalg.eigh(H)
    valsPHI, vectsPHI = eigsh(H2, k=2, which='SA')
    #vals,_=np.linalg.eigh(H)
    print("The eigenvalues of the GS and the 1st excited state are ",valsPHI[0]," and ",valsPHI[1])
    print("The eigenvectors of the GS and the 1st excited state are ",vectsPHI[:,0]," and ",vectsPHI[:,1])
    EIGENVECTS_PHIEXT.extend([vectsPHI[:,0],vectsPHI[:,1]])
    print(EIGENVECTS_PHIEXT)
    print("Eigenvalues and eigenvectors calculated")
    #Cos_theta
    Expval_costheta_0=calculate_expval(vectsPHI[:,0],cos_theta)
    Expval_costheta_1=calculate_expval(vectsPHI[:,1],cos_theta)
    #Phi
    Expval_phi_0=calculate_expval(vectsPHI[:,0],phi)
    Expval_phi_1=calculate_expval(vectsPHI[:,1],phi)
    #N_phi
    Expval_N_phi_0=calculate_expval(vectsPHI[:,0],N_phi_extended)
    Expval_N_phi_1=calculate_expval(vectsPHI[:,1],N_phi_extended)
    #n_theta
    Expval_n_theta_0=calculate_expval(vectsPHI[:,0],n_theta_extended)
    Expval_n_theta_1=calculate_expval(vectsPHI[:,1],n_theta_extended)
    #Overlap between the states of the same value of ng
    Overlap=calculate_overlap(vectsPHI[:,0],vectsPHI[:,1])
    print("Overlap = ",Overlap)
    #TOTALS
    Overlaps_PHIEXT.append(Overlap)
    Expvals_costheta_PHIEXT.extend([Expval_costheta_0,Expval_costheta_1])
    Expvals_phi_PHIEXT.extend([Expval_phi_0,Expval_phi_1])
    Expvals_N_phi_PHIEXT.extend([Expval_N_phi_0,Expval_N_phi_1])
    Expvals_n_theta_PHIEXT.extend([Expval_n_theta_0,Expval_n_theta_1])

Step for phi_ext =  3.087932051951622
Hamiltonian built, len(H)= 4372281
The eigenvalues of the GS and the 1st excited state are  1.757010989930689  and  1.7869969328573547
The eigenvectors of the GS and the 1st excited state are  [ 1.20380451e-18  9.21806257e-20 -1.64062579e-18 ... -2.14088927e-17
  1.92637368e-17  1.17196938e-16]  and  [-2.32923290e-17 -7.54574690e-19 -4.37036586e-18 ... -2.72873831e-17
 -4.93052732e-18 -1.07229553e-16]
[array([ 1.20380451e-18,  9.21806257e-20, -1.64062579e-18, ...,
       -2.14088927e-17,  1.92637368e-17,  1.17196938e-16]), array([-2.32923290e-17, -7.54574690e-19, -4.37036586e-18, ...,
       -2.72873831e-17, -4.93052732e-18, -1.07229553e-16])]
Eigenvalues and eigenvectors calculated
Overlap =  2.7733391199176196e-30
Step for phi_ext =  3.195253255227964
Hamiltonian built, len(H)= 4372281
The eigenvalues of the GS and the 1st excited state are  1.757010989930792  and  1.7869969328574145
The eigenvectors of the GS and the 1st excited state are  [ 1.4

EXPECTATION VALUES FOR THE FIRST SET OF VALUES FOR THE ENERGIES

In [28]:
#VARYING NG
print("VARYING NG")
print("Exp values of cos_theta varying ng are ",Expvals_costheta_NG)
print("Exp values of phi varying ng are ",Expvals_phi_NG)
print("Exp values of N_phi varying ng are ",Expvals_N_phi_NG)
print("Exp values of n_theta varying ng are ",Expvals_n_theta_NG)
#VARYING PHI_EXT
print("VARYING PHI_EXT")
print("Exp values of cos_theta varying phi_ext are ",Expvals_costheta_PHIEXT)
print("Exp values of phi varying phi_ext are ",Expvals_phi_PHIEXT)
print("Exp values of N_phi varying phi_ext are ",Expvals_N_phi_PHIEXT)
print("Exp values of n_theta varying phi_ext are ",Expvals_n_theta_PHIEXT)

VARYING NG
Exp values of cos_theta varying ng are  [-1.0416272807254437e-11, 1.0457222102171499e-11, -1.5176257833861661e-12, 1.5158652653627915e-12]
Exp values of phi varying ng are  [-5.417013674275537e-12, 5.439459068531517e-12, -7.880772559059929e-13, 7.678037716198863e-13]
Exp values of N_phi varying ng are  [0.0875642916296936, 0.0915154491000944, 0.08756429162969262, 0.09151544910008405]
Exp values of n_theta varying ng are  [0.0743367322010737, 0.9216791656471212, 0.9256632677989239, 0.07832083435286863]
VARYING PHI_EXT
Exp values of cos_theta varying phi_ext are  [1.0750531247601136, -1.0693290471791248, -1.0750531247601383, 1.069329047179117]
Exp values of phi varying phi_ext are  [0.5533295551481093, -0.5641098274123524, -0.5533295551483852, 0.5641098274122824]
Exp values of N_phi varying phi_ext are  [0.08817876837785914, 0.09078329014962477, 0.0881787683779437, 0.0907832901496056]
Exp values of n_theta varying phi_ext are  [0.4999999999997501, 0.5000000000002629, 0.5000000

In [29]:
Overlaps_UP_NG.extend([calculate_overlap(EIGENVECTS_NG[0],EIGENVECTS_NG[1]),calculate_overlap(EIGENVECTS_NG[2],EIGENVECTS_NG[3])])
Overlaps_UP_PHIEXT.extend([calculate_overlap(EIGENVECTS_PHIEXT[0],EIGENVECTS_PHIEXT[1]),calculate_overlap(EIGENVECTS_PHIEXT[2],EIGENVECTS_PHIEXT[3])])
Overlaps_SIDE_NG.extend([calculate_overlap(EIGENVECTS_NG[0],EIGENVECTS_NG[2]),calculate_overlap(EIGENVECTS_NG[1],EIGENVECTS_NG[3])])
Overlaps_SIDE_PHIEXT.extend([calculate_overlap(EIGENVECTS_PHIEXT[0],EIGENVECTS_PHIEXT[2]),calculate_overlap(EIGENVECTS_PHIEXT[1],EIGENVECTS_PHIEXT[3])])
Overlaps_CROSSED_NG.extend([calculate_overlap(EIGENVECTS_NG[0],EIGENVECTS_NG[3]),calculate_overlap(EIGENVECTS_NG[1],EIGENVECTS_NG[2])])
Overlaps_CROSSED_PHIEXT.extend([calculate_overlap(EIGENVECTS_PHIEXT[0],EIGENVECTS_PHIEXT[3]),calculate_overlap(EIGENVECTS_PHIEXT[1],EIGENVECTS_PHIEXT[2])])
print(Overlaps_UP_NG)
print(Overlaps_UP_PHIEXT)
print(Overlaps_SIDE_NG)
print(Overlaps_SIDE_PHIEXT)
print(Overlaps_CROSSED_NG)
print(Overlaps_CROSSED_PHIEXT)

[2.728145353527852e-30, 1.1675500583254164e-30]
[2.7733391199176196e-30, 4.44966854351227e-30]
[3.109368611152513e-23, 3.11223169788531e-23]
[3.9577672078246333e-25, 3.905556787776251e-25]
[0.9999472625990677, 0.9999472625990731]
[0.9999271167136526, 0.9999271167136402]


## $\text{2. Plot for } E_{Cs} = \frac{1}{20}$, $E_{CJ} = 1$, $E_L = \frac{1}{16}$, $\varphi_{ext} = \pi$, $\alpha = i \left(\frac{E_{CJ}}{E_L}\right)^{1/4} = 2i$.

In [30]:
# Calculations 2

for n2 in ng2:
    print("Step for ng = ",n2)
    H3=Hamiltonian_0pi(E_J_2,E_Cs_2,E_Cj_2,E_L_2,n2,phi_ext_val,alpha2)
    print("Hamiltonian built, len(H)=",len(H3)**2)
    #vals2,vects2=np.linalg.eigh(H2)
    vals2NG, vects2NG = eigsh(H3, k=2, which='SA')
    #vals2,_=np.linalg.eigh(H3)
    print("The eigenvalues of the GS and the 1st excited state are ",vals2NG[0]," and ",vals2NG[1])
    print("The eigenvectors of the GS and the 1st excited state are ",vects2NG[:,0]," and ",vects2NG[:,1])
    EIGENVECTS2_NG.extend([vects2NG[:,0],vects2NG[:,1]])
    print(EIGENVECTS2_NG)
    print("Eigenvalues and eigenvectors calculated")
    #Cos_theta
    Expval2_costheta_0=calculate_expval(vects2NG[:,0],cos_theta)
    Expval2_costheta_1=calculate_expval(vects2NG[:,1],cos_theta)
    #Phi
    Expval2_phi_0=calculate_expval(vects2NG[:,0],phi)
    Expval2_phi_1=calculate_expval(vects2NG[:,1],phi)
    #N_phi
    Expval2_N_phi_0=calculate_expval(vects2NG[:,0],N_phi_extended)
    Expval2_N_phi_1=calculate_expval(vects2NG[:,1],N_phi_extended)
    #n_theta
    Expval2_n_theta_0=calculate_expval(vects2NG[:,0],n_theta_extended)
    Expval2_n_theta_1=calculate_expval(vects2NG[:,1],n_theta_extended)
    #Overlap between the states of the same value of ng
    Overlap2=calculate_overlap(vects2NG[:,0],vects2NG[:,1])
    print("Overlap = ",Overlap2)
    #TOTALS
    Overlaps2_NG.append(Overlap2)
    Expvals2_costheta_NG.extend([Expval2_costheta_0,Expval2_costheta_1])
    Expvals2_phi_NG.extend([Expval2_phi_0,Expval2_phi_1])
    Expvals2_N_phi_NG.extend([Expval2_N_phi_0,Expval2_N_phi_1])
    Expvals2_n_theta_NG.extend([Expval2_n_theta_0,Expval2_n_theta_1])

Step for ng =  0.49625
Hamiltonian built, len(H)= 4372281
The eigenvalues of the GS and the 1st excited state are  0.27440622062540665  and  0.27586942228479316
The eigenvectors of the GS and the 1st excited state are  [-1.28798817e-18  4.21373585e-18 -1.78633613e-18 ...  1.84080214e-16
 -2.29135450e-17 -3.95890630e-17]  and  [-5.54264790e-18 -1.72775279e-17  8.67361128e-18 ...  6.14890184e-17
 -4.35897855e-18 -6.38590185e-17]
[array([-1.28798817e-18,  4.21373585e-18, -1.78633613e-18, ...,
        1.84080214e-16, -2.29135450e-17, -3.95890630e-17]), array([-5.54264790e-18, -1.72775279e-17,  8.67361128e-18, ...,
        6.14890184e-17, -4.35897855e-18, -6.38590185e-17])]
Eigenvalues and eigenvectors calculated
Overlap =  4.862462389795233e-31
Step for ng =  0.50375
Hamiltonian built, len(H)= 4372281
The eigenvalues of the GS and the 1st excited state are  0.2744062206254137  and  0.2758694222847878
The eigenvectors of the GS and the 1st excited state are  [-3.95215610e-19 -1.04942889e-18

In [31]:
# Calculations 2

for phi2 in phi_ext2:
    print("Step for phi_ext = ",phi2)
    H4=Hamiltonian_0pi(E_J_2,E_Cs_2,E_Cj_2,E_L_2,ng_val,phi2,alpha2)
    print("Hamiltonian built, len(H)=",len(H4)**2)
    #vals,vects=np.linalg.eigh(H)
    vals2PHI, vects2PHI = eigsh(H4, k=2, which='SA')
    #vals,_=np.linalg.eigh(H)
    print("The eigenvalues of the GS and the 1st excited state are ",vals2PHI[0]," and ",vals2PHI[1])
    print("The eigenvectors of the GS and the 1st excited state are ",vects2PHI[:,0]," and ",vects2PHI[:,1])
    EIGENVECTS2_PHIEXT.extend([vects2PHI[:,0],vects2PHI[:,1]])
    print(EIGENVECTS2_PHIEXT)
    print("Eigenvalues and eigenvectors calculated")
    #Cos_theta
    Expval2_costheta_0=calculate_expval(vects2PHI[:,0],cos_theta)
    Expval2_costheta_1=calculate_expval(vects2PHI[:,1],cos_theta)
    #Phi
    Expval2_phi_0=calculate_expval(vects2PHI[:,0],phi)
    Expval2_phi_1=calculate_expval(vects2PHI[:,1],phi)
    #N_phi
    Expval2_N_phi_0=calculate_expval(vects2PHI[:,0],N_phi_extended)
    Expval2_N_phi_1=calculate_expval(vects2PHI[:,1],N_phi_extended)
    #n_theta
    Expval2_n_theta_0=calculate_expval(vects2PHI[:,0],n_theta_extended)
    Expval2_n_theta_1=calculate_expval(vects2PHI[:,1],n_theta_extended)
    #Overlap between the states of the same value of ng
    Overlap2=calculate_overlap(vects2PHI[:,0],vects2PHI[:,1])
    print("Overlap = ",Overlap2)
    #TOTALS
    Overlaps2_PHIEXT.append(Overlap2)
    Expvals2_costheta_PHIEXT.extend([Expval2_costheta_0,Expval2_costheta_1])
    Expvals2_phi_PHIEXT.extend([Expval2_phi_0,Expval2_phi_1])
    Expvals2_N_phi_PHIEXT.extend([Expval2_N_phi_0,Expval2_N_phi_1])
    Expvals2_n_theta_PHIEXT.extend([Expval2_n_theta_0,Expval2_n_theta_1])

Step for phi_ext =  3.087932051951622
Hamiltonian built, len(H)= 4372281
The eigenvalues of the GS and the 1st excited state are  0.2744052831572177  and  0.2758684882163911
The eigenvectors of the GS and the 1st excited state are  [ 7.45449940e-18  1.63816047e-19  7.92487294e-18 ... -3.39903970e-17
 -5.41870354e-17  1.15726176e-16]  and  [ 5.36835677e-18  2.21684769e-19 -2.35461093e-21 ... -1.57736946e-16
  3.34136408e-17 -1.45926109e-16]
[array([ 7.45449940e-18,  1.63816047e-19,  7.92487294e-18, ...,
       -3.39903970e-17, -5.41870354e-17,  1.15726176e-16]), array([ 5.36835677e-18,  2.21684769e-19, -2.35461093e-21, ...,
       -1.57736946e-16,  3.34136408e-17, -1.45926109e-16])]
Eigenvalues and eigenvectors calculated
Overlap =  1.4914401489334754e-30
Step for phi_ext =  3.195253255227964
Hamiltonian built, len(H)= 4372281
The eigenvalues of the GS and the 1st excited state are  0.2744052831572139  and  0.2758684882163605
The eigenvectors of the GS and the 1st excited state are  [ 8

EXPECTATION VALUES FOR THE SECOND SET OF VALUES FOR THE ENERGIES

In [32]:
#VARYING NG
print("VARYING NG")
print("Exp values of cos_theta varying ng are ",Expvals2_costheta_NG)
print("Exp values of phi varying ng are ",Expvals2_phi_NG)
print("Exp values of N_phi varying ng are ",Expvals2_N_phi_NG)
print("Exp values of n_theta varying ng are ",Expvals2_n_theta_NG)
#VARYING PHI_EXT
print("VARYING PHI_EXT")
print("Exp values of cos_theta varying phi_ext are ",Expvals2_costheta_PHIEXT)
print("Exp values of phi varying phi_ext are ",Expvals2_phi_PHIEXT)
print("Exp values of N_phi varying phi_ext are ",Expvals2_N_phi_PHIEXT)
print("Exp values of n_theta varying phi_ext are ",Expvals2_n_theta_PHIEXT)

VARYING NG
Exp values of cos_theta varying ng are  [-3.807941001625906e-12, 3.8222551894291374e-12, -1.2944640064357398e-12, 1.2927270284314459e-12]
Exp values of phi varying ng are  [-7.612962613411929e-13, 7.611989565170725e-13, -2.58663997070221e-13, 2.585850995228319e-13]
Exp values of N_phi varying ng are  [0.04405150929309551, 0.044219905124188066, 0.044051509293093996, 0.04421990512418525]
Exp values of n_theta varying ng are  [0.012119939464361242, 0.9875864842028906, 0.9878800605356375, 0.012413515797104594]
VARYING PHI_EXT
Exp values of cos_theta varying phi_ext are  [1.0850347542364278, -1.078788729130867, -1.0850347542364025, 1.0787887291308773]
Exp values of phi varying phi_ext are  [0.2170405766180944, -0.2191471508665695, -0.21704057661807252, 0.21914715086659714]
Exp values of N_phi varying phi_ext are  [0.04406669809423212, 0.04419447354001976, 0.04406669809422786, 0.04419447354002322]
Exp values of n_theta varying phi_ext are  [0.49999999999602435, 0.5000000000039695,

In [33]:
Overlaps2_UP_NG.extend([calculate_overlap(EIGENVECTS2_NG[0],EIGENVECTS2_NG[1]),calculate_overlap(EIGENVECTS2_NG[2],EIGENVECTS2_NG[3])])
Overlaps2_UP_PHIEXT.extend([calculate_overlap(EIGENVECTS2_PHIEXT[0],EIGENVECTS2_PHIEXT[1]),calculate_overlap(EIGENVECTS2_PHIEXT[2],EIGENVECTS2_PHIEXT[3])])
Overlaps2_SIDE_NG.extend([calculate_overlap(EIGENVECTS2_NG[0],EIGENVECTS2_NG[2]),calculate_overlap(EIGENVECTS2_NG[1],EIGENVECTS2_NG[3])])
Overlaps2_SIDE_PHIEXT.extend([calculate_overlap(EIGENVECTS2_PHIEXT[0],EIGENVECTS2_PHIEXT[2]),calculate_overlap(EIGENVECTS2_PHIEXT[1],EIGENVECTS2_PHIEXT[3])])
Overlaps2_CROSSED_NG.extend([calculate_overlap(EIGENVECTS2_NG[0],EIGENVECTS2_NG[3]),calculate_overlap(EIGENVECTS2_NG[1],EIGENVECTS2_NG[2])])
Overlaps2_CROSSED_PHIEXT.extend([calculate_overlap(EIGENVECTS2_PHIEXT[0],EIGENVECTS2_PHIEXT[3]),calculate_overlap(EIGENVECTS2_PHIEXT[1],EIGENVECTS2_PHIEXT[2])])
print(Overlaps2_UP_NG)
print(Overlaps2_UP_PHIEXT)
print(Overlaps2_SIDE_NG)
print(Overlaps2_SIDE_PHIEXT)
print(Overlaps2_CROSSED_NG)
print(Overlaps2_CROSSED_PHIEXT)

[4.862462389795233e-31, 3.10641258278484e-33]
[1.4914401489334754e-30, 2.8649883365887606e-64]
[5.612350767765598e-24, 5.609222490736063e-24]
[5.665121788183039e-24, 5.6725232016705656e-24]
[0.9999990445567553, 0.9999990445567521]
[0.9999512894938998, 0.9999512894939044]


In [35]:
#EIGVECTS_NG = np.array(EIGENVECTS_NG)
#np.save('EIGVECTS_NG_EG_4.npy', EIGVECTS_NG)
#EIGVECTS_PHIEXT = np.array(EIGENVECTS_PHIEXT)
#np.save('EIGVECTS_PHIEXT_EG_4.npy', EIGVECTS_PHIEXT)
#EIGVECTS2_NG = np.array(EIGENVECTS2_NG)
#np.save('EIGVECTS2_NG_EG_4.npy', EIGVECTS2_NG)
#EIGVECTS2_PHIEXT = np.array(EIGENVECTS2_PHIEXT)
#np.save('EIGVECTS2_PHIEXT_EG_4.npy', EIGVECTS2_PHIEXT)